### ISSUE TITLE
Implement Viking Instruction Parser

### ISSUE THREAD

**Issue by JasonBrave** [FRC6854/VIKING#12]
Viking instruction specification https://github.com/FRC6854/Instruction

**Comment by Raminh05** [comment]
@Ow1e Owen what are you doing?

**Comment by Raminh05** [comment]
@Ow1e it's due this Thursday trust me bro

**Comment by oshaulz** [comment]
This was probably to adventurous to add :(

**Comment by JasonBrave** [comment]
This have to be implemented for next year competition. (If @Ow1e wants to use viking instruction encoding)

**Comment by oshaulz** [comment]
We have no need for a Instruction system when we have PathPlanner which is easier to work with.
